# check-file-naming-light.ps1
# Lightweight File Naming Convention Checker for cFish.io
# Version: 1.0.0
# Date: 2025-03-14

# Define the expected file naming pattern
# Format: [prefix]-[department].[function]-[description]-[date].[extension]
# Example: ucf-u7.3-directory-structure-20250315.ps1

# Define the naming convention regex pattern
$namingPattern = "^ucf-u[1-7]\.[1-9]-[a-z0-9-]+-\d{8}\.[a-z0-9]+$"

##### Initialize counters
$totalFilesChecked = 0
$compliantCount = 0
$nonCompliantCount = 0

##### Create an output file
$outputFile = "file-naming-compliance-summary.md"
$date = Get-Date -Format "yyyy-MM-dd"

##### Write header to the output file
@"
# cFish.io File Naming Compliance Summary
**Generated:** $date

This report summarizes the compliance of files with the UcF naming convention.

## File Naming Convention
```
ucf-[department].[function]-[description]-[date].[extension]
```

Example: `ucf-u7.3-directory-structure-20250315.ps1`

## Summary Statistics

"@ | Out-File -FilePath $outputFile -Encoding utf8

##### Get all files in the UcF directories
Write-Host "Scanning UcF directories for files..." -ForegroundColor Yellow
$uDirs = Get-ChildItem -Path . -Directory -Filter "U*-*"

foreach ($dir in $uDirs) {
    Write-Host "Checking files in $($dir.Name)..." -ForegroundColor Cyan
    $files = Get-ChildItem -Path $dir.FullName -Recurse -File
    
    foreach ($file in $files) {
        $totalFilesChecked++
        $fileName = $file.Name
        
        ##### Check if file name matches the pattern
        if ($fileName -match $namingPattern) {
            $compliantCount++
        }
        else {
            $nonCompliantCount++
        }
    }
}

##### Calculate compliance percentage
$compliancePercentage = 0
if ($totalFilesChecked -gt 0) {
    $compliancePercentage = [math]::Round(($compliantCount / $totalFilesChecked) * 100, 2)
}

##### Write summary to output file
@"
- **Total Files Checked:** $totalFilesChecked
- **Compliant Files:** $compliantCount
- **Non-Compliant Files:** $nonCompliantCount
- **Compliance Percentage:** $compliancePercentage%

## Next Steps

1. Review files in UcF directories that don't comply with the naming convention
2. Create a plan for standardizing file names
3. Implement naming standardization in phases, prioritizing critical files

_Generated by check-file-naming-light.ps1 on $date_
"@ | Out-File -FilePath $outputFile -Encoding utf8 -Append

##### Display summary in console
Write-Host "`nFile Naming Compliance Summary:" -ForegroundColor Green
Write-Host "Total Files Checked: $totalFilesChecked" -ForegroundColor White
Write-Host "Compliant Files: $compliantCount" -ForegroundColor Green
Write-Host "Non-Compliant Files: $nonCompliantCount" -ForegroundColor Yellow
Write-Host "Compliance Percentage: $compliancePercentage%" -ForegroundColor Cyan
Write-Host "`nSummary has been saved to: $outputFile" -ForegroundColor Green 
